### ISSUE TITLE
chore: update to MicroPython 1.19

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-micropython#103]
MicroPython 1.19 hasn't been released yet, but will be soon. There are more than the usual update tasks with the version (mostly due to new mpy ABI version), so making note of them here:

- [x] Publish `mpy-cross-v6` Javascript package.
- [x] Publish `mpy-cross-v6` Python package.
- [x] Make use of `MP_REGISTER_MODULE` macro.
- [ ] Build and use mboot on SPIKE hubs.
- [x] Enable importing modules with u prefix on unix variants, e.g. allow `import umath`.

**Comment by laurensvalk** [comment]
The rebase step itself seems to have gone without a hitch: https://github.com/pybricks/micropython/tree/pybricks-v3.2

> Make use of MP_REGISTER_MODULE macro.

So the only commit I had to skip was:

https://github.com/pybricks/micropython/commit/bf835f45e56c381b2ae9134a8414c84315dd64dd

I mainly just did the rebase to ensure that <*py/builtinimport.c: Support builtin-package as nested modules.*> still rebases without conflicts, and it does. I'll check in on our next call before proceeding.

**Comment by laurensvalk** [comment]
Perhaps not technically related to this upgrade, but I've added one item above nonetheless. Maybe we can do it while we're at it.

It would nice if we can import the same modules on the virtualhub as on the real hubs. Currently this gives an import error:

```python
from umath import sin, pi
```

**Comment by dlech** [comment]
> ```python
> from umath import sin, pi
> ```

:wink: https://github.com/micropython/micropython/pull/8844
