### ISSUE TITLE
Program run indication incorrect if Bluetooth is not connected

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#11]
Since the recent changes to the system lights and `sys/hmi`, the permanent program does not run if Bluetooth is not connected.

The permanent program is still working on SPIKE Prime since it isn't waiting for Bluetooth.

I've just updated the `main.py` scripts to just wait a few seconds so it's easier to test this workflow while we are revising the system lights and UI.

**Comment by dlech** [comment]
I think the program actually does run still but just the indication light doesn't work. This is because we don't have a way to stop Bluetooth advertising yet without connecting Bluetooth first.

**Comment by laurensvalk** [comment]
Next step: do program run animation similar to light matrix animation during program run for now.
