### ISSUE TITLE
Add .vscode folder with c_cpp_properties

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#20]
Since the lead developers are both using Visual Studio Code, it would be useful to have the `c_cpp_properties` file in this repository so we don't have to recreate it every time.

**Comment by dlech** [comment]
VS Code 1.52 includes a new feature that we can use to work around the problem I mentioned.

**Comment by dlech** [comment]
Added in https://github.com/pybricks/pybricks-micropython/commit/184d900e56d9351d71ff057c4f39acf45a8a080f
