### ISSUE TITLE
Some artifacts are not being uploaded

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#28]
As of recently, some uploads are missing entirely, while some ZIP files do not have all the contents (such as `install_pybricks.llsp` in primehub).

https://github.com/pybricks/pybricks-micropython/actions?query=workflow%3ABuild+branch%3Amaster

![image](https://user-images.githubusercontent.com/12326241/99717196-62c74c00-2aa9-11eb-970e-63d9d3f3aec0.png)

Thanks @GusJansson for reporting this.

**Comment by dlech** [comment]
Should be fixed now.

**Comment by laurensvalk** [comment]
Looking good, thank you!
