### ISSUE TITLE
Some checks do not complete on pull requests

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#33]
https://github.com/pybricks/pybricks-micropython/commit/a2babe9d76d574a16281d2a8d1ad0056d79b1a1a fixed pull requests not failing, but we still have some checks that never complete:

![image](https://user-images.githubusercontent.com/12326241/101887056-a68b0e00-3b9c-11eb-94d3-e9d2221a79d5.png)

**Comment by dlech** [comment]
I found where this was coming from in the github settings. The test names changed due to https://github.com/pybricks/pybricks-micropython/commit/a042f5af8edd61fb9304cac528e5cf20a6c15313
