### ISSUE TITLE
Turn off devices on shutdown if power still on

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#36]
On Prime Hub, the following should not stay on after auto-shutdown if USB is still connected:

- Light matrix
- Hub status light
- I/O ports
- Bluetooth
- USB (except battery charging function)

Future:
- LCD display (NXT)
- Sound

_Originally posted by @laurensvalk in https://github.com/pybricks/support/issues/79#issuecomment-743728863_

**Comment by laurensvalk** [comment]
This also happens for other hubs as long as you are holding down the button.

**Comment by dlech** [comment]
I think this is done enough to close. Battery charging and NXT support are tracked in separate. issues. All other items are done.

**Comment by laurensvalk** [comment]
> All other items are done.

There seems to be one more case:

```python
from pybricks.hubs import ThisHub
from pybricks.tools import wait

hub = ThisHub()

print(hub.system.reset_reason())
wait(100)
hub.system.reset(0) # Already applied support#379, so here doing power-off

# The animation stays on and freezes
```
