### ISSUE TITLE
Implement battery charging on Prime/Inventor hubs

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-micropython#41]
- hub runtime needs to be able to shut down most things while keeping the main loop running (also see #36)
- needs to detect charger type
- needs to control charger chip
- needs to indicate status using LED
  - traditional LEGO chargers use red for charging and green for full
  - latest firmware from LEGO also uses yellow - for fault/error

**Comment by Vinz1911** [comment]
This is a feature which I currently really miss. Is there maybe something I can support/help here to make this work? 😊

**Comment by laurensvalk** [comment]
While you're welcome to contribute directly to the driver code, there are other ways to help as well.

Perhaps the best way to help is to get other developers involved, who might contribute code or sponsor the project.

That is easier said than done, though. We're currently not as active online and on social media as we could be. Creating fun projects with Pybricks and sharing them online is usually a good start.

**Comment by dlech** [comment]
The fundamentals are done now.
