### ISSUE TITLE
boot.py for REPL

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-micropython#47]
When using the REPL, it is tedious to import everything. It would be helpful to have a frozen `boot.py` that runs when the REPL is started:

```python
from pybricks.hubs import XHub
from pybricks.pupdevices import Motor, ...
from pybricks.parameters import Color, ...
from pybricks.tools import wait, ...

hub = XHub()
```

**Comment by laurensvalk** [comment]
https://github.com/pybricks/pybricks-micropython/commits/work3 has an alternate solution where we don't have to maintain a `boot.py`.

**Comment by dlech** [comment]
nice
