### ISSUE TITLE
Add download and run tests

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#52]
[Recently added tests](https://github.com/pybricks/pybricks-micropython/tree/master/tests/pup/sensors) mainly focus on motors and sensors. In principle, it suffices to run these from only one host since the focus is on the robot side of things.

We could also use a few scripts that test the download and run process. We'd want to run these on as many devices and browsers as we want to support.

- I/O only + wait
- Long/short duration scripts
- Big/small scripts
- Tight loop print
- Raising systemexits / keyboard interrupts / other exceptions

**Comment by laurensvalk** [comment]
For now, it's sufficient to run these manually from Pybricks Code.

**Comment by dlech** [comment]
I've pushed a few of these that I did last week before I distracted with other things. I would still like to do some tests that create .mpy files of various sizes (e.g. 1k, 2k, 4k, etc.).

**Comment by dlech** [comment]
size tests are done
