### ISSUE TITLE
Messaging API support on technic hub (Lego 88102 brick)

### ISSUE THREAD

**Issue by massimiliano-mantione** [pybricks/pybricks-micropython#71]
In the documentation, I see that the messaging API is implemented only for the EV3 brick.
I'd like to know if it is technically feasible to implement it for the Lego Technic Hub (88102 brick).
If yes, if possible I'd like a few pointers on how to approach the implementation.
Ultimately I'd give it a try and provide a pull request implementing it (I'd really need it for a project of mine).

**Comment by laurensvalk** [comment]
Yes, this is possible. It is being discussed here: https://github.com/pybricks/support/issues/262
