### ISSUE TITLE
chore: fix import of uasyncio module

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-micropython#91]
Since updating to MicroPython v1.18, CI tests for uasyncio are failing. We don't currently use uasyncio, so the tests are disabled. However, we should figure out why and fix it. I suspect that https://github.com/pybricks/micropython/commit/20a2982dfed3b4478c9da1f29e962b6797924293 is breaking imports since the `uasyncio` module does funny imports in https://github.com/micropython/micropython/blob/v1.18/extmod/uasyncio/__init__.py.

**Comment by laurensvalk** [comment]
Besides fixing the import, it deletes this `ImportError` https://github.com/pybricks/micropython/commit/204e59c227c71135a9ab24a08fd646f0657f7d21 which seems like it got accidentally added to the wrong commit.
